name: 'marketing_analytics_dbt'
version: '1.0.0'
config-version: 2

profile: 'marketing_analytics_dbt'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  marketing_analytics_dbt:
    staging:
      +materialized: view
      +schema: staging
      marketing:
        +materialized: view
        +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
      marketing:
        +materialized: view
        +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
      marketing:
        +materialized: table
        +schema: marts

seeds:
  marketing_analytics_dbt:
    marketing:
      +schema: marketing_raw
